import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';
import ClientLayout from '../../ClientLayout';

const STATUS_COLORS = {
  'New':          '#1d4ed8',
  'Contacted':    '#d97706',
  'In Progress':  '#7c3aed',
  'Closed Won':   '#16a34a',
  'Closed Lost':  '#dc2626',
};

const FILTER_OPTIONS = ['All', 'New', 'Contacted', 'In Progress', 'Closed Won', 'Closed Lost'];

const COLUMNS = ['Date', 'Name', 'Email', 'Phone', 'Municipality', 'System Type', 'Estimated Price', 'Status', 'Actions'];

function formatDate(dateStr) {
  const d = new Date(dateStr);
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

export default function Leads() {
  const { profile } = useAuth();

  const navigate = useNavigate();

  const [leads, setLeads]             = useState([]);
  const [loading, setLoading]         = useState(true);
  const [search, setSearch]           = useState('');
  const [activeFilter, setActiveFilter] = useState('All');
  const [hoveredRow, setHoveredRow]   = useState(null);

  useEffect(() => {
    if (!profile?.client_id) return;
    fetchLeads();
  }, [profile]);

  async function fetchLeads() {
    setLoading(true);
    const { data, error } = await supabase
      .from('leads')
      .select('*')
      .eq('client_id', profile.client_id)
      .order('created_at', { ascending: false });
    if (!error && data) setLeads(data);
    setLoading(false);
  }

  async function updateStatus(leadId, newStatus) {
    await supabase.from('leads').update({ status: newStatus }).eq('id', leadId);
    setLeads(prev => prev.map(l => l.id === leadId ? { ...l, status: newStatus } : l));
  }

  function handleExportCSV() {
    if (leads.length === 0) return;
    const headers = ['Date', 'Name', 'Email', 'Phone', 'Municipality', 'System Type', 'Estimated Price', 'Status'];
    const rows = leads.map(l => [
      formatDate(l.created_at),
      l.name || '',
      l.email || '',
      l.phone || '',
      l.municipality || '',
      l.answers?.wastewaterType || '',
      l.estimated_price ?? '',
      l.status || '',
    ]);
    const csv = [headers, ...rows].map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'leads.csv';
    a.click();
    URL.revokeObjectURL(url);
  }

  // Computed stats
  const now = new Date();
  const thisMonthCount = leads.filter(l => {
    const d = new Date(l.created_at);
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).length;

  const avgPrice = leads.length > 0
    ? Math.round(leads.reduce((sum, l) => sum + (Number(l.estimated_price) || 0), 0) / leads.length)
    : null;

  // Filtered list
  const filteredLeads = leads.filter(l => {
    const q = search.toLowerCase();
    const matchesSearch = !q ||
      (l.name  || '').toLowerCase().includes(q) ||
      (l.email || '').toLowerCase().includes(q);
    const matchesFilter = activeFilter === 'All' || l.status === activeFilter;
    return matchesSearch && matchesFilter;
  });

  return (
    <ClientLayout title="Leads">

      {/* ── Top row ── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#0d1117', margin: 0 }}>Leads</h1>
          <p style={{ fontSize: '13px', color: '#9ca3af', margin: '4px 0 0' }}>
            All leads generated by your estimator tool.
          </p>
        </div>
        <button
          type="button"
          onClick={handleExportCSV}
          style={{
            border: '1px solid #e5e7eb',
            backgroundColor: '#ffffff',
            color: '#111827',
            borderRadius: '10px',
            padding: '10px 18px',
            fontSize: '13px',
            cursor: 'pointer',
            fontWeight: '500',
          }}
        >
          Export CSV
        </button>
      </div>

      {/* ── Stat cards ── */}
      <div style={{ display: 'flex', gap: '16px', marginTop: '24px' }}>

        {/* Card 1 — Total Leads */}
        <div style={{ flex: 1, backgroundColor: '#ffffff', border: '1px solid #f0f0f0', borderRadius: '14px', padding: '20px' }}>
          <div style={{
            width: '42px', height: '42px', borderRadius: '10px',
            backgroundColor: '#0d3d2a',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '20px', color: '#ffffff',
          }}>▤</div>
          <p style={{ fontSize: '12px', color: '#9ca3af', margin: '16px 0 4px', fontWeight: '500' }}>Total Leads</p>
          <p style={{ fontSize: '22px', fontWeight: '700', color: '#0d1117', margin: 0 }}>
            {loading ? '—' : leads.length}
          </p>
        </div>

        {/* Card 2 — This Month */}
        <div style={{ flex: 1, backgroundColor: '#ffffff', border: '1px solid #f0f0f0', borderRadius: '14px', padding: '20px' }}>
          <div style={{
            width: '42px', height: '42px', borderRadius: '10px',
            backgroundColor: '#dbeafe',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '20px', color: '#1d4ed8',
          }}>◎</div>
          <p style={{ fontSize: '12px', color: '#9ca3af', margin: '16px 0 4px', fontWeight: '500' }}>This Month</p>
          <p style={{ fontSize: '22px', fontWeight: '700', color: '#0d1117', margin: 0 }}>
            {loading ? '—' : thisMonthCount}
          </p>
        </div>

        {/* Card 3 — Conversion Rate */}
        <div style={{ flex: 1, backgroundColor: '#ffffff', border: '1px solid #f0f0f0', borderRadius: '14px', padding: '20px' }}>
          <div style={{
            width: '42px', height: '42px', borderRadius: '10px',
            backgroundColor: '#dcfce7',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '20px', color: '#16a34a',
          }}>▤</div>
          <p style={{ fontSize: '12px', color: '#9ca3af', margin: '16px 0 4px', fontWeight: '500' }}>Conversion Rate</p>
          <p style={{ fontSize: '22px', fontWeight: '700', color: '#0d1117', margin: 0 }}>—</p>
        </div>

        {/* Card 4 — Avg Estimate Value */}
        <div style={{ flex: 1, backgroundColor: '#ffffff', border: '1px solid #f0f0f0', borderRadius: '14px', padding: '20px' }}>
          <div style={{
            width: '42px', height: '42px', borderRadius: '10px',
            backgroundColor: '#fef9c3',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '20px', color: '#ca8a04',
          }}>⊞</div>
          <p style={{ fontSize: '12px', color: '#9ca3af', margin: '16px 0 4px', fontWeight: '500' }}>Avg Estimate Value</p>
          <p style={{ fontSize: '22px', fontWeight: '700', color: '#0d1117', margin: 0 }}>
            {loading ? '—' : avgPrice !== null ? `${avgPrice.toLocaleString()} kr` : '—'}
          </p>
        </div>

      </div>

      {/* ── Search + filter row ── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '28px', flexWrap: 'wrap' }}>

        <input
          type="text"
          placeholder="Search by name or email..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          style={{
            flex: 1,
            minWidth: '200px',
            height: '42px',
            padding: '0 16px',
            fontSize: '13px',
            border: '1px solid #e5e7eb',
            borderRadius: '10px',
            outline: 'none',
            color: '#111827',
            backgroundColor: '#ffffff',
            boxSizing: 'border-box',
          }}
        />

        <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
          {FILTER_OPTIONS.map(opt => (
            <button
              key={opt}
              type="button"
              onClick={() => setActiveFilter(opt)}
              style={{
                padding: '7px 14px',
                fontSize: '12px',
                borderRadius: '8px',
                border: activeFilter === opt ? 'none' : '1px solid #e5e7eb',
                backgroundColor: activeFilter === opt ? '#0d3d2a' : '#ffffff',
                color: activeFilter === opt ? '#ffffff' : '#6b7280',
                cursor: 'pointer',
                fontWeight: activeFilter === opt ? '600' : '400',
              }}
            >
              {opt}
            </button>
          ))}
        </div>

      </div>

      {/* ── Table ── */}
      <div style={{
        marginTop: '16px',
        backgroundColor: '#ffffff',
        border: '1px solid #f0f0f0',
        borderRadius: '14px',
        overflow: 'hidden',
      }}>

        {/* Header */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: '100px 130px 180px 120px 130px 130px 140px 140px 80px',
          backgroundColor: '#fafafa',
          borderBottom: '1px solid #f0f0f0',
          padding: '12px 20px',
        }}>
          {COLUMNS.map(col => (
            <span key={col} style={{
              fontSize: '11px',
              fontWeight: '600',
              color: '#9ca3af',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
            }}>
              {col}
            </span>
          ))}
        </div>

        {/* Body */}
        {loading ? (
          <div style={{ padding: '40px 20px', textAlign: 'center', fontSize: '13px', color: '#9ca3af' }}>
            Loading leads...
          </div>
        ) : filteredLeads.length === 0 ? (
          <div style={{ padding: '40px 20px', textAlign: 'center', fontSize: '13px', color: '#9ca3af', marginTop: '40px' }}>
            {leads.length === 0
              ? 'No leads yet. Your leads will appear here once customers use your estimator tool.'
              : 'No leads match your search or filter.'}
          </div>
        ) : (
          filteredLeads.map(lead => (
            <div
              key={lead.id}
              onMouseEnter={() => setHoveredRow(lead.id)}
              onMouseLeave={() => setHoveredRow(null)}
              style={{
                display: 'grid',
                gridTemplateColumns: '100px 130px 180px 120px 130px 130px 140px 140px 80px',
                padding: '12px 20px',
                fontSize: '13px',
                color: '#374151',
                borderBottom: '1px solid #f7f7f7',
                backgroundColor: hoveredRow === lead.id ? '#fafef9' : '#ffffff',
                alignItems: 'center',
              }}
            >
              {/* Date */}
              <span>{formatDate(lead.created_at)}</span>

              {/* Name */}
              <span style={{ fontWeight: '500', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {lead.name || '—'}
              </span>

              {/* Email */}
              <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: '#6b7280' }}>
                {lead.email || '—'}
              </span>

              {/* Phone */}
              <span style={{ color: '#6b7280' }}>{lead.phone || '—'}</span>

              {/* Municipality */}
              <span style={{ color: '#6b7280' }}>{lead.municipality || '—'}</span>

              {/* System Type */}
              <span style={{ color: '#6b7280' }}>
                {lead.answers?.wastewaterType || '—'}
              </span>

              {/* Estimated Price */}
              <span style={{ fontWeight: '500' }}>
                {lead.estimated_price != null
                  ? `${Number(lead.estimated_price).toLocaleString()} kr`
                  : '—'}
              </span>

              {/* Status dropdown */}
              <span>
                <select
                  value={lead.status || 'New'}
                  onChange={e => updateStatus(lead.id, e.target.value)}
                  style={{
                    border: '1px solid #e5e7eb',
                    borderRadius: '6px',
                    padding: '4px 8px',
                    fontSize: '12px',
                    color: STATUS_COLORS[lead.status] || '#374151',
                    fontWeight: '600',
                    backgroundColor: '#ffffff',
                    cursor: 'pointer',
                    outline: 'none',
                  }}
                >
                  {['New', 'Contacted', 'In Progress', 'Closed Won', 'Closed Lost'].map(s => (
                    <option key={s} value={s}>{s}</option>
                  ))}
                </select>
              </span>

              {/* Actions */}
              <span>
                <button
                  type="button"
                  onClick={() => navigate(`/client/leads/${lead.id}`)}
                  style={{
                    fontSize: '12px',
                    color: '#0d3d2a',
                    backgroundColor: 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                    fontWeight: '600',
                    padding: 0,
                  }}
                >
                  View
                </button>
              </span>

            </div>
          ))
        )}

      </div>

    </ClientLayout>
  );
}
